const TEST_ENV_DEFAULTS: Record<string, string> = {
  NODE_ENV: 'test',
  HOST: '127.0.0.1',
  PORT: '3000',
  EMAIL_DELIVERY_PROVIDER: 'development_override',
  EMAIL_FROM_NAME: 'Hyperwood Test',
  PRIMARY_MARKET_CURRENCY: 'USD',
  SUPPORTED_MARKET_CURRENCIES: 'USD,BRL',
  CORS_ALLOWED_ORIGINS: 'http://localhost:8081,http://127.0.0.1:8081',
  API_RATE_LIMIT_WINDOW_SECONDS: '60',
  API_RATE_LIMIT_MAX_REQUESTS: '120',
  AUTH_RATE_LIMIT_WINDOW_SECONDS: '60',
  AUTH_RATE_LIMIT_MAX_REQUESTS: '100',
  DATABASE_URL: 'postgres://postgres:postgres@127.0.0.1:5432/hyperwood_test',
  SESSION_TTL_HOURS: '720',
  SESSION_IDLE_TTL_HOURS: '24',
  EMAIL_VERIFICATION_TTL_MINUTES: '60',
  MAILERSEND_API_TOKEN: '',
  MAILERSEND_DOMAIN: 'test-r9084zvxq6jgw63d.mlsender.net',
  MAILERSEND_FROM_EMAIL: 'no-reply@test-r9084zvxq6jgw63d.mlsender.net',
  MAILERSEND_WEBHOOK_SIGNING_SECRET: '',
  MFA_CHALLENGE_TTL_MINUTES: '10',
  MFA_ACTION_AUTHORIZATION_TTL_MINUTES: '5',
  LOGIN_RISK_WINDOW_MINUTES: '15',
  LOGIN_MAX_FAILURES_PER_EMAIL: '5',
  LOGIN_MAX_FAILURES_PER_IP: '10',
  TOTP_ISSUER: 'Hyperwood Test',
  TOTP_ENCRYPTION_KEY:
    '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
  API_KEY_ENCRYPTION_KEY:
    'abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789',
  API_HMAC_MAX_SKEW_SECONDS: '300',
  API_HMAC_NONCE_TTL_SECONDS: '300',
  FUNDING_PROVIDER_WEBHOOK_SECRET: 'test-webhook-secret',
  FUNDING_PROVIDER_WEBHOOK_MAX_SKEW_SECONDS: '300',
  FUNDING_PROVIDER_CALLBACK_DELAY_MINUTES: '30',
  REALTIME_STREAM_STALE_SECONDS: '45',
  MARKET_SETTLEMENT_FAILURE_MINUTES: '30',
  INTERNAL_BOOTSTRAP_TOKEN: 'test-bootstrap-token',
};

export function applyTestEnv(overrides: Record<string, string> = {}) {
  for (const [key, value] of Object.entries({
    ...TEST_ENV_DEFAULTS,
    ...overrides,
  })) {
    if (!process.env[key]) {
      process.env[key] = value;
    }
  }
}
